spring:
  profiles:
    active: ${ACTIVE_PROFILE:dev}
    include:
      - server
      
  application:
    name: spring-blog-api
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/testdb}
    username: ${SPRING_DATASOURCE_USERNAME:testuser}
    password: ${SPRING_DATASOURCE_PASSWORD:testpass}
    driver-class-name: org.postgresql.Driver
  jpa:
    show_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  mail:
    host: ${SPRING_MAIL_HOST:localhost}
    port: ${SPRING_MAIL_PORT:1025}
    username: ${SPRING_MAIL_USERNAME:mailuser}
    password: ${SPRING_MAIL_PASSWORD:mailpass}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    org:
      springframework:
        security: DEBUG
  file:
    name: logs/spring-blog-api.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

security:
  jwt:
    secret_key: ${JWT_SECRET_KEY:testsecret}
    expiration_time: ${JWT_EXPIRATION_TIME:3600000}

client:
  app:
    url: ${CLIENT_APP_URL:http://localhost:3000}
